version: '3'
services: 
    nodeApp: 
        build: .
        command: npm run dev
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        depends_on:
            - postgres
            
    postgres: 
        image: postgres:latest 
        ports: 
            - '5432:5432'
        environment: 
            POSTGRES_USER: 'admin' 
            POSTGRES_PASSWORD: 'password' 
            POSTGRES_DB: 'accounts'
        volumes: 
            - ./init:/docker-entrypoint-initdb.d/
    